index:
    path: /
    controller: App\Controller\DefaultController::index
adminIndex:
    path: /admin
    controller: App\Controller\AdminController::index
adminOrder:
    path: /admin/orders
    controller: App\Controller\AdminController::order

